version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: groupe5user
      WORDPRESS_DB_PASSWORD: Groupe5pwd
      WORDPRESS_DB_NAME: db_mysql
    volumes:
      - "/mnt/wp-content:/var/www/html/wp-content"
    deploy:
      placement:
        constraints: [node.labels.role == worker]
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_mysql
      MYSQL_USER: groupe5user
      MYSQL_PASSWORD: Groupe5pwd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "/mnt/mysql:/var/lib/mysql"
    deploy:
      placement:
        constraints: [node.labels.role == worker]
